name: Rust

on:
  push:
    branches: [ "anybuild" ]
  # pull_request:
    # branches: [ "master" ]

defaults:
  run:
    shell: bash

permissions:
  id-token: write

env:
  AB_ClusterUri: https://westus2.anybuild-test.microsoft.com/clusters/992d6b3f-0a13-496e-900a-88f78089abc5
  AB_ClientApplicationId: 18653f49-2ded-4b7a-baeb-aa14099278ca
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - name: Linux x86_64 stable Normal
          os: ubuntu-latest
          rust: stable
          CARGO_CMD: cargo
        - name: Linux x86_64 stable AnyBuild
          os: ubuntu-latest
          CARGO_CMD: build/cargo

    steps:
    - uses: actions/checkout@v3
    - name: Install AnyBuild Client for Linux
      run: |
        set -euo pipefail
        wget -O- https://anybuild.azureedge.net/clientreleases/bootstrapper.sh | bash

    - name: Dump Environment
      run: env
    - name: Build
      run: ${{ matrix.CARGO_CMD }} build --verbose
      env:
          AB_SECRET: ${{ secrets.AB_SECRET }}
    - name: Test
      run: ${{ matrix.CARGO_CMD }} test --verbose
      env:
          AB_SECRET: ${{ secrets.AB_SECRET }}
